/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ColorModal: typeof import('./src/components/ColorModal.vue')['default']
    CommonToolbar: typeof import('./src/components/CommonToolbar.vue')['default']
    GlowButton: typeof import('./src/components/GlowButton.vue')['default']
    ImageModal: typeof import('./src/components/ImageModal.vue')['default']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonBackButton: typeof import('@ionic/vue')['IonBackButton']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonCardContent: typeof import('@ionic/vue')['IonCardContent']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonFooter: typeof import('@ionic/vue')['IonFooter']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRange: typeof import('@ionic/vue')['IonRange']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonSpinner: typeof import('@ionic/vue')['IonSpinner']
    IonText: typeof import('@ionic/vue')['IonText']
    IonTextarea: typeof import('@ionic/vue')['IonTextarea']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    MoreMenuPopover: typeof import('./src/components/MoreMenuPopover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
