/* generated by chatgpt3 */
export interface HumanReadableDateTime {
  dateTime: string;
  date: Date;
}

// create a datetime string that's 17 characters in length
export function getDateTime(): HumanReadableDateTime {
  // Create a new Date object
  const date = new Date();

  // Get the date and time components
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  const seconds = String(date.getSeconds()).padStart(2, "0");
  const milliseconds = String(date.getMilliseconds()).padStart(3, "0");

  // Concatenate the components into the filename string
  const dateTime = `${year}${month}${day}${hours}${minutes}${seconds}${milliseconds}`;

  // Output the filename string
  return { dateTime, date };
}
